- name: wait for all VMs to come online
  hosts: rhel_kvm
  tags: infrastructure
  gather_facts: false
  tasks:
    - name: check that all vms are online
      wait_for:
        host: "{{ item.1.ip }}"
        state: started
        connect_timeout: 5
        timeout: 300
        port: 22
      delegate_to: 127.0.0.1
      become: false
      ignore_errors: true
      with_subelements:
        - "{{ vmenator.vms }}"
        - nics
