---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - cf-vars.yml
  vars: 
    type: ui
    db: false
    ui: true
    wk: false
    num: 1
  roles:
    - {role: 'roles/jritenour.osp-cf-miq'}

- hosts: cfui
  remote_user: root
  vars_files:
    - cf-vars.yml
  vars:
    zone_name: UI
    zone_desc: UI Zone
    db_server: "{{ hostvars[groups['cfdb'][0]]['ansible_default_ipv4']['address'] }}"
  roles: 
    - {role: 'roles/jritenour.cf-miq-ui'}
