---
- name: Create a template from qcow
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    engine_url: https://engine.pod3.mpc/ovirt-engine/api
    engine_user: admin@internal
    engine_password: "{{ rhv_pass }}"
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    validate_certs: False

    qcow_url: http://172.16.2.10:8888/images/rhel75t.qcow
    template_cluster: Default
    template_name: rhel75
    template_memory: 16GiB
    template_cpu: 4
    template_disk_size: 40GiB
    template_disk_storage: data

  roles:
    - oVirt.image-template
