- name: rhhi storage domains
  hosts: localhost

  tasks:

  - name: include vars again
    include_vars:
      file: group_vars/all/vars

  - name: Authenticate to RHV-M
    ovirt_auth:
     url: "https://{{ rhvurl }}/ovirt-engine/api"
     username: "admin@internal"
     password: "{{ rhv_pass }}"
     insecure: true

  -  ovirt_storage_domains:
      auth: "{{ ovirt_auth }}"
      name: data
      host: "{{ rhv4_mpc_hostname }}"
      data_center: Default
      domain_function: data
      glusterfs:
        address: "{{ mpc_rhv4_ip }}"
        path: /data
        mount_options: backup-volfile-servers={{ mpc_rhv2_ip }}:{{ mpc_rhv3_ip }}

  -  ovirt_storage_domains:
      auth: "{{ ovirt_auth }}"
      name: iso
      host: "{{ rhv4_mpc_hostname }}"
      domain_function: iso
      data_center: Default
      glusterfs:
        address: "{{ mpc_rhv4_ip }}"
        path: /iso
        mount_options: backup-volfile-servers={{ mpc_rhv2_ip }}:{{ mpc_rhv3_ip }}

  -  ovirt_storage_domains:
      auth: "{{ ovirt_auth }}"
      name: vmstore
      host: "{{ rhv4_mpc_hostname }}"
      domain_function: data
      data_center: Default
      glusterfs:
        address: "{{ mpc_rhv4_ip }}"
        path: /vmstore
        mount_options: backup-volfile-servers={{ mpc_rhv2_ip }}:{{ mpc_rhv3_ip }}
