- hosts: localhost
  vars:
    remove_engine:
      - 'HostedEngine'
  tasks:
    - name: include vars again
      include_vars:
        file: group_vars/all/vars

    - name: Authenticate to RHV-M
      ovirt_auth:
       url: "https://{{ rhvurl }}/ovirt-engine/api"
       username: "admin@internal"
       password: "{{ rhv_pass }}"
       insecure: true

    - name: List vms
      ovirt_vms_facts:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
        nested_attributes:
          - description

    - name: set vms
      set_fact:
         vm: "{{ item.name }}: {{ item.snapshots |
         map(attribute='description') | join(',') }}"
      with_items: "{{ ovirt_vms }}"
      loop_control:
        label: "{{ item.name }}"
      register: all_vms

    - name: debug vm list
      debug: msg="{{ all_vms.results }}"

    - name: make a list
      set_fact: vms="{{ all_vms.results | map(attribute='item.name') |list }}"

    - name: Copy using the 'content' for inline data
      copy:
        content: "{{ vms }}"
        dest: /root/redhat-truck/redbox/vmsbeforeshutdown.txt

    - name: Print vms
      debug:
        var: vms

    - set_fact:
       vms: "{{ vms | difference(remove_engine) }}"

    - name: Print vms
      debug:
        var: vms


    - name: shutdown vms except engine
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: "stopped"
        wait: true
        name: "{{ item }}"
      with_items: "{{ vms }}"

    - name: set gloabl maintenance mode
      shell: hosted-engine --set-maintenance --mode=global
      delegate_to: 172.16.30.23
      register: maintenance_mode
 

    - name: shutdown hosted-engine
      shell: hosted-engine --vm-shutdown
      delegate_to: "{{ item }}"
      register: stopped
      ignore_errors: true
      with_items:
        - "{{ rhv4_mpc_hostname }}"
        - "{{ rhv3_mpc_hostname }}"
        - "{{ rhv2_mpc_hostname }}"

    - name: check for engine to be down
      shell: hosted-engine --vm-status
      register: "engine_down"
      retries: 100
      unitl: engine_down.find("good") == -1
      delegate_to: 172.16.30.23
      #until: "{{ engine_down | good }}"

 
    - name: ipmireboot
      shell: ipmitool -I lanplus -H {{ item }} -U admin -P admin chassis power soft
      with_items:
        - "{{ ipmi2 }}"
        - "{{ ipmi3 }}"
        - "{{ ipmi4 }}"
      delegate_to: localhost
 
