- name: rhhi network
  hosts: localhost

  tasks:

  - name: Authenticate to RHV-M
    ovirt_auth:
     url: "https://10.0.5.203/ovirt-engine/api"
     username: "admin@internal"
     password: "redhat"
     insecure: true

  # tasks file for ldomb-rhhi
  - name: add gluster
    ovirt_networks:
      auth: "{{ ovirt_auth }}"
      data_center: Default
      name: gluster
      #vlan_tag: 1
      clusters:
      - name: default
        gluster: true
        required: false
      state: present

  - name: Bonds
    ovirt_host_networks:
      auth: "{{ ovirt_auth }}"
      name: rhv4.local.redhat-demo.com
      bond:
        name: bond0
        mode: 2
        interfaces:
          - eno3
          - eno4
      networks:
        - name: gluster
          boot_protocol: static
          address: 10.0.4.12
          netmask: 255.255.255.0
          gateway: 10.0.4.1
          version: v4


  - name: sleep a little
    pause:
      seconds: 30

  - name: add hosts
    ovirt_hosts:
      auth: "{{ ovirt_auth }}"
      cluster: Default
      name: "{{ item }}"
      password: redhat
      address: "{{ item }}"
      override_iptables: true
      hosted_engine: deploy
    with_items: 
      - rhv3.local.redhat-demo.com
      - rhv2.local.redhat-demo.com

  - name: sleep a little
    pause:
      seconds: 30

  - name: Bonds rhv2.local.redhat-demo.com
    ovirt_host_networks:
      auth: "{{ ovirt_auth }}"
      name: rhv2.local.redhat-demo.com
      bond:
        name: bond0
        mode: 2
        interfaces:
          - eno3
          - eno4
      networks:
        - name: gluster
          boot_protocol: static
          address: 10.0.4.10
          netmask: 255.255.255.0
          gateway: 10.0.4.1
          version: v4

  - name: Bonds rhv3.local.redhat-demo.com
    ovirt_host_networks:
      auth: "{{ ovirt_auth }}"
      name: rhv3.local.redhat-demo.com
      bond:
        name: bond0
        mode: 2
        interfaces:
          - eno3
          - eno4
      networks:
        - name: gluster
          boot_protocol: static
          address: 10.0.4.11
          netmask: 255.255.255.0
          gateway: 10.0.4.1
          version: v4
