---
# tasks file for roles/rhel_idm
- name: set hostname
  hostname:
    name: "{{ rhel_idm.hostname_short }}.{{ domain }}"

- name: add line to hosts file for self
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^{{ inventory_hostname }}"
    line: "{{ inventory_hostname }} {{ rhel_idm.hostname_short }}.{{ domain }} {{ rhel_idm.hostname_short }}"

- name: enable the needed rhel repositories
  yum_repository:
    name: "{{ item }}"
    description: "{{ item }}"
    baseurl: "{{ local_repo_url }}{{ item }}"
    gpgcheck: no
    enabled: yes
    file: rhn-local
    state: present
  with_items:
    - "{{ rhel_idm.repos }}"
  when: not register_rhn

- name: enable the needed rhel repositories
  command: subscription-manager repos --enable={{ item }}
  with_items:
    - "{{ rhel_idm.repos }}"
  when: register_rhn

- name: update packages
  yum:
    name: '*'
    state: latest
  register: yum_result
  async: 1000
  poll: 30

- name: check Kernel is the Latest
  shell: if [ $(uname -r) == $(rpm -q kernel | tail -n 1 | sed -e 's/kernel-//g') ] ; then echo no ; else echo reboot; fi
  ignore_errors: true
  register: reboot_hint

- name: make sure cloud-init is not installed
  yum:
    name: cloud-init
    state: absent

- name: install IPA packages
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - "{{ rhel_idm.packages }}"

- name: restart server to get updated kernel
  shell: sleep 2 && shutdown -r now "Ansible restart triggered for latest kernel"
  async: 1
  poll: 0
  ignore_errors: true
# TODO: force reboot for now because of dbus/dnsmasq error
#  when: yum_result.changed or reboot_hint.stdout.find("reboot") != -1

- name: waiting for IDM server to come back online
  wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    delay: 10
    connect_timeout: 5
    timeout: 300
    port: 22
  delegate_to: 127.0.0.1
  become: false
  ignore_errors: true

#TODO add boolean for forwarders
- name: Setup IPA Server
  #command: ipa-server-install -Uq -r '{{ rhel_idm.realm }}' -n '{{ domain }}' --allow-zone-overlap -p '{{ rhel_idm.dm_pwd }}' -a '{{ rhel_idm.admin_pwd }}' --setup-dns --auto-reverse --reverse-zone '{{ rhel_idm.reverse_zone }}' --forwarder '{{ rhel_idm.forward_ip }}'
  command: ipa-server-install -Uq -r '{{ rhel_idm.realm }}' -n '{{ domain }}' --allow-zone-overlap -p '{{ rhel_idm.dm_pwd }}' -a '{{ rhel_idm.admin_pwd }}' --setup-dns --auto-reverse --reverse-zone '{{ rhel_idm.reverse_zone }}' --no-forwarders

- name: waiting for IDM services to come up
  wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    delay: 10
    connect_timeout: 5
    timeout: 300
    port: 443
  delegate_to: 127.0.0.1
  become: false
  ignore_errors: true

- name: enable dynamic updates on dns zones
  command: "echo {{ rhel_idm.admin_pwd }} | kinit admin && ipa dnszone-mod {{ item }} --dynamic-update=TRUE"
  with_items:
    - "{{ domain }}"
    - "{{ rhel_idm.reverse_zone}}"

- name: enable allow ptr sync on dns zones
  command: "echo {{ rhel_idm.admin_pwd }} | kinit admin && ipa dnszone-mod --allow-sync-ptr=1 {{ item }}"
  with_items:
    - "{{ domain }}"
    - "{{ rhel_idm.reverse_zone}}"

- name: add users to IDM
  ipa_user:
    ipa_host: "{{ rhel_idm.hostname_short }}.{{ domain }}"
    ipa_user: admin
    ipa_pass: "{{ rhel_idm.admin_pwd }}"
    state: present
    uid: "{{ item.username }}"
    password: "{{ item.password }}"
    displayname: "{{ item.display_name }}"
    givenname: "{{ item.first_name }}"
    sn: "{{ item.last_name }}"
    title: "{{ item.title }}"
    mail:
    - "{{ item.email }}"
    telephonenumber:
    - "{{ item.phone }}"
  with_items:
    - "{{ rhel_idm.users }}"

- name: add forward DNS entries to IDM
  ipa_dnsrecord:
    ipa_host: "{{ rhel_idm.hostname_short }}.{{ domain }}"
    ipa_user: admin
    ipa_pass: "{{ rhel_idm.admin_pwd }}"
    state: present
    zone_name: "{{ domain }}"
    record_name: "{{ item.hostname }}"
    record_type: "A"
    record_value: "{{ item.ip_address }}"
  with_items:
    - "{{ rhel_idm.dns_records }}"

- name: add reverse DNS entries to IDM
  ipa_dnsrecord:
    ipa_host: "{{ rhel_idm.hostname_short }}.{{ domain }}"
    ipa_user: admin
    ipa_pass: "{{ rhel_idm.admin_pwd }}"
    state: present
    zone_name: "{{ rhel_idm.reverse_zone }}"
    record_name: "{{ item.reverse_record }}"
    record_type: 'PTR'
    record_value: "{{ item.hostname }}.{{ domain }}"
  with_items:
    - "{{ rhel_idm.dns_records }}"

- name: remove temporary nameserver from /etc/resolv.conf file
  lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver {{ dns_server_public }}"
    state: absent
