---
# tasks file for netgear-xs716T

- name: run show commands
  telnet:
    pause: 2
    user: admin
    password: password
    port: 60000
    login_prompt: "User:"
    prompts:
      - "[u'(XS716T) >',u'#']"
    command:
      - show vlan
