---
# tasks file for jritenour.cf-miq-wk
  - name: Join CloudForms/ManageIQ region
    command: appliance_console_cli -K  {{ db_server }} --sshlogin {{ ssh_user }} --sshpassword {{ cf_ssh_pass }} --hostname {{ db_server }} --password {{ cf_db_pass }}

  - name: Wait for CloudForms services to come up
    wait_for:
      host: "{{ansible_eth0.ipv4.address }}"
      port: "443"
      delay: "120"
      timeout: "600"
      state: "started"

  - name: Configure Roles
    command: "/var/www/miq/vmdb/bin/rails runner 'MiqServer.my_server.set_config(:server => {:role => \"user_interface,web_services,websocket\"})'"

  - name: restart EVM
    service:
      name: evmserverd
      state: restarted

  - name: Create Zone
    shell: "/var/www/miq/vmdb/bin/rails runner 'Zone.create(:name => \"{{ zone_name }}\", :description => \"{{ zone_desc }}\")'"

  - name: Move UI server to UI Zone
    command: "/var/www/miq/vmdb/bin/rails runner 'MiqServer.my_server.set_config(:server => {:zone => \"{{ zone_name}}\"})'"

  - name: Copy the chrony.conf template file
    template: src=chrony.conf.j2 dest={{ chrony_config_location }}
    notify:
    - restart chrony

