---
# tasks file for ldomb-pxeserver
#TODO: need to enable the proper services instead
- name: disable firewalld
  systemd:
    name: firewalld
    enabled: false
    state: stopped

- name: install necessary packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - xinetd
    - syslinux
    - tftp-server
    - httpd
    - dnsmasq
    - bind

- name: copy dnsmsaq in place
  copy:
    src: files/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: ['Restart dnsmasq']

- name: copy bind zones in place
  copy:
    src: files/dnsmasq.conf
    dest: /var/named/{{ item }}
    owner: named
    group: root
    mode: 0644
  with_items:
    - 101.168.192.in-addr.arpa.zone
    - 2.168.192.in-addr.arpa.zone
    - 1.168.192.in-addr.arpa.zone
    - 0.168.192.in-addr.arpa.zone
    - rhhi.lab.zone
  notify: ['Restart named']

- name: copy named.conf
  copy:
    src: files/named.conf
    dest: /etc/named.conf
    owner: root
    group: root
  notify: ['Restart named']

- name: copy syslinux to /var/lib/tftpboot
  shell: "rsync -av /usr/share/syslinux/* /var/lib/tftpboot/"

- name: copy pxelinux.cfg recursive
  copy:
    directory_mode: true
    src: files/pxelinux.cfg
    dest: /var/lib/tftpboot/
    owner: root
    group: root

- name: Download rhvh2.tar.gz
  get_url:
    url: http://{{ web_ip }}/content/rhvh2.tar.gz
    dest: /var/www/html/rhvh2.tar.gz
    mode: 0640

- name: untar rhvh2.tar.gz
  unarchive:
    remote_src: yes
    src: /var/www/html/rhvh2.tar.gz
    dest: /var/www/html


- name: copy kickstarts
  copy:
    src: files/{{ item }}
    dest: /var/www/html/{{item}}
    owner: root
    group: root
    mode: 0644
  with_items:
    - rhvh1-ks.cfg
    - rhvh2-ks.cfg
    - rhvh3-ks.cfg
    - rhvh4-ks.cfg

- name: start xinted
  service:
    name: xinetd
    state: started
    enabled: yes

- name: enable service httpd and ensure it is not masked
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - httpd
    - named
