---
# defaults for all vars
domain: two.hattrick.lab
dns_server_local: 172.16.21.15
dns_server_public: 8.8.8.8
git_repo: https://github.com/redhat-kejones/hattrick

# defaults file for roles/rhel_kvm
rhel_kvm:
  hostname_full: kvm.{{ domain }}
  disks:
    root: sda
    libvirt_images: sdb
    content: sdc
  repos:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-rh-common-rpms
  packages:
    - 'screen'
    - 'wget'
    - 'vim'
    - 'tree'
    - 'yum-utils'
    - 'git'
    - 'qemu-kvm'
    - 'qemu-img'
    - 'libvirt'
    - 'virt-install'
    - 'libvirt-client'
    - 'libvirt-python'
    - 'libguestfs-tools-c'
    - 'rhel-guest-image-7'
    - 'ansible'
