---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - 'ocp-vars.yml'
  vars:
    type: node
    master: false
    node: true
    image_uid: rhel74
    flavor_name: ocp1.node
  roles:
    - ocp-osp
  tasks: 
    - name: add master server to inventory
      add_host:
        hostname: "{{ master1 }}"
        ansible_ssh_user: "{{ ssh_user }}"
        groupname: master

- hosts:
    - master
#    - node
  remote_user: root
  become: true
  vars_files:
    - 'ocp-vars.yml'
  tasks:
    - name: copy over ansible.cfg
      copy:
        src: files/.ansible.cfg
        dest: /root/.ansible.cfg

#    - name: add newnodes line
#      lineinfile:
#        dest: /etc/ansible/hosts
#        state: present
#        insertafter: '^nodes'
#        line: 'new_nodes'
#      when: "'master' in group_names"
#
#    - name: add newnodes block
#      blockinfile:
#        insertafter: EOF
#        path: /etc/ansible/hosts
#        content: |
#          [new_nodes]
#          {{ hostvars[groups['node'][0]]['ansible_default_ipv4']['address'] }}
#      when: "'master' in group_names"

- hosts: '!localhost'
  remote_user: cloud-user
  become: true
  vars_files:
    - 'ocp-vars.yml'
  roles:
    - rhel_common
    - ocp-scaleup
